language: php

php:
  - 5.3
  - 5.4

branches:
  only:
    - dev

env:  
  - CAKE_VERSION=master DB=mysql

before_script: bundle exec rake db:migrate
script: bundle exec rake test

notifications:
  email: false
